services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsTimeline\EventListener\NewContentElementPreviewRenderer:
    tags:
      - name: event.listener
        identifier: 'flexform-process'
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
